CC = gcc
SOURCES1 = ./1/main.c ./1/hash.c
SOURCES2 = ./2/main.c ./2/hash.c
SOURCES3 = ./3/main.c ./3/heap.c
SOURCES4 = ./4/main.c ./4/heap.c
all: q1 q2 q3 q4
q1: 
	$(CC) $(SOURCES1) -o ./1/q1.o  -Wall
q2: 
	$(CC) $(SOURCES2) -o ./2/q2.o  -Wall
q3: 
	$(CC) $(SOURCES3) -o ./3/q3.o  -Wall
q4: 
	$(CC) $(SOURCES4) -o ./4/q4.o  -Wall